on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@master
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Create ACR
      id: create-acr
      run: |
        az acr create -n containerokeee -g containerokeeeab9f-rg --location "East US" --sku Standard --admin-enabled
        echo "::set-output name=acr_username::`az acr credential show -n containerokeee --query username | xargs`"
        echo "::set-output name=acr_password::`az acr credential show -n containerokeee --query passwords[0].value | xargs`"
        echo "::add-mask::`az acr credential show -n containerokeee --query passwords[0].value | xargs`"

    - uses: azure/docker-login@v1
      with:
        login-server: containerokeee.azurecr.io
        username: ${{ steps.create-acr.outputs.acr_username }}
        password: ${{ steps.create-acr.outputs.acr_password }}

    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/Dockerfile" -f  "svcs/data" -t containerokeee.azurecr.io/myakscluster:${{ github.sha }} --label dockerfile-path=svcs/data
        docker push containerokeee.azurecr.io/myakscluster:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      id: login
      with:
         kubeconfig: ${{ secrets.aks_myakscluster_kubeConfig }}
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep okeescapeall | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace okeescapeall`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: okeescapeall
        container-registry-url: containerokeee.azurecr.io
        container-registry-username: ${{ steps.create-acr.outputs.acr_username }}
        container-registry-password: ${{ steps.create-acr.outputs.acr_password }}
        secret-name: myaksclusterdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: okeescapeall
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          containerokeee.azurecr.io/myakscluster:${{ github.sha }}
        imagepullsecrets: |
          myaksclusterdockerauth   
