on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@master
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Create ACR
      id: create-acr
      run: |
        az acr create -n dockerfiletilesrv -g dockerfiletilesrv970e-rg --location "East US" --sku Standard --admin-enabled
        echo "::set-output name=acr_username::`az acr credential show -n dockerfiletilesrv --query username | xargs`"
        echo "::set-output name=acr_password::`az acr credential show -n dockerfiletilesrv --query passwords[0].value | xargs`"
        echo "::add-mask::`az acr credential show -n dockerfiletilesrv --query passwords[0].value | xargs`"

    - uses: azure/docker-login@v1
      with:
        login-server: dockerfiletilesrv.azurecr.io
        username: ${{ steps.create-acr.outputs.acr_username }}
        password: ${{ steps.create-acr.outputs.acr_password }}

    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/Dockerfile.tilesrv" -f  "svcs/data" -t dockerfiletilesrv.azurecr.io/myakscluster:${{ github.sha }} --label dockerfile-path=svcs/data
        docker push dockerfiletilesrv.azurecr.io/myakscluster:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      id: login
      with:
         kubeconfig: ${{ secrets.aks_myakscluster_kubeConfig }}
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep dockerfiletilesrv | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace dockerfiletilesrv`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: dockerfiletilesrv
        container-registry-url: dockerfiletilesrv.azurecr.io
        container-registry-username: ${{ steps.create-acr.outputs.acr_username }}
        container-registry-password: ${{ steps.create-acr.outputs.acr_password }}
        secret-name: myaksclusterdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: dockerfiletilesrv
        manifests: |
          manifests/deployment-1.yml
          manifests/service-1.yml
        images: |
          dockerfiletilesrv.azurecr.io/myakscluster:${{ github.sha }}
        imagepullsecrets: |
          myaksclusterdockerauth   
